-- ==========================================================
-- Migração: Pastas do Banco de Ideias
-- Execute este SQL no Supabase Dashboard > SQL Editor
-- ==========================================================

-- 1. Criar tabela de pastas de ideias
CREATE TABLE IF NOT EXISTS idea_folders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  color TEXT DEFAULT 'bg-violet-500',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Adicionar coluna folder_id na tabela library (para ideias)
ALTER TABLE library ADD COLUMN IF NOT EXISTS folder_id BIGINT REFERENCES idea_folders(id) ON DELETE SET NULL;

-- 3. Habilitar RLS na tabela de pastas
ALTER TABLE idea_folders ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de acesso
CREATE POLICY "Users can view their own folders" ON idea_folders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own folders" ON idea_folders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own folders" ON idea_folders FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own folders" ON idea_folders FOR DELETE USING (auth.uid() = user_id);
