-- ==========================================
-- SUPABASE SQL SCHEMA FOR AI STUDIO APP
-- Copy and paste this entire file into the Supabase SQL Editor and click "Run"
-- ==========================================

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create a storage bucket for avatars (if it doesn't exist)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true) 
ON CONFLICT (id) DO NOTHING;

-- Set up storage policies for avatars
CREATE POLICY "Avatar images are publicly accessible." ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
CREATE POLICY "Users can upload their own avatar." ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);
CREATE POLICY "Users can update their own avatar." ON storage.objects FOR UPDATE USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);
CREATE POLICY "Users can delete their own avatar." ON storage.objects FOR DELETE USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

-- 3. Create profiles table tied to auth.users
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  handle TEXT,
  avatarUrl TEXT,
  bio TEXT,
  role TEXT DEFAULT 'user', -- 'admin' or 'user'
  subscription_status TEXT,
  subscription_plan TEXT,
  stripe_customer_id TEXT,
  last_payment_date TIMESTAMP WITH TIME ZONE,
  token_balance INTEGER DEFAULT 0,
  is_unlimited BOOLEAN DEFAULT false,
  features JSONB DEFAULT '[]'::jsonb,
  saved_audience TEXT,
  saved_product TEXT,
  level INTEGER DEFAULT 1,
  xp INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Note: To update an existing database you must run the following ALTER TABLE commands
-- as CREATE TABLE IF NOT EXISTS will skip if the table exists.
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS subscription_status TEXT;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS subscription_plan TEXT;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_payment_date TIMESTAMP WITH TIME ZONE;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS token_balance INTEGER DEFAULT 0;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_unlimited BOOLEAN DEFAULT false;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS features JSONB DEFAULT '[]'::jsonb;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS saved_audience TEXT;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS saved_product TEXT;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0;

-- 4. Create library table
CREATE TABLE IF NOT EXISTS library (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL,
  content JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Set up Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE library ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Create a secure function to check admin status without triggering RLS
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
DECLARE
  admin_status BOOLEAN;
BEGIN
  SELECT role = 'admin' INTO admin_status FROM profiles WHERE id = auth.uid();
  RETURN COALESCE(admin_status, false);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Allow admins to view all profiles using the secure function
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT USING (
  public.is_admin()
);

-- Library policies
CREATE POLICY "Users can view their own library items" ON library FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own library items" ON library FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own library items" ON library FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own library items" ON library FOR DELETE USING (auth.uid() = user_id);

-- 6. Trigger to create a profile automatically when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles ("id", "email", "name", "handle", "avatarUrl", "role")
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'name', 'Novo Usuário'), 
    COALESCE(new.raw_user_meta_data->>'handle', 'user_' || substr(new.id::text, 1, 6)),
    'https://picsum.photos/seed/' || new.id || '/200/200',
    COALESCE(new.raw_user_meta_data->>'role', 'user')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================
-- INSTRUCTIONS TO CREATE THE MASTER ADMIN:
-- ==========================================
-- After running this script, go to Authentication -> Users in Supabase and create your first user.
-- Then, come back to the SQL Editor and run this line (replace with your email):
-- UPDATE profiles SET role = 'admin' WHERE email = 'your_email@example.com';
